import { ICharacterInfo } from "@/types/interface";

import * as cryo from "./cryo/0";
import * as pyro from "./pyro/0";
import * as anemo from "./anemo/0";
import * as electro from "./electro/0";
import * as geo from "./geo/0";
import * as dendro from "./dendro/0";
import * as hydro from "./hydro/0";

// .replaceAll("%", '').replaceAll(/[\u4e00-\u9fff]+/g, "").replaceAll("\t",",").split(",").map(i=>Math.round(i*100)/10000)
export const Character: ICharacterInfo[] = [
  electro.Ineffa,
  cryo.Skirk,
  hydro.Dahlia,
  cryo.Escoffier,
  anemo.Ifa,
  electro.Varesa,
  electro.Iansan,
  anemo.Mizuki,
  anemo.LanYan,
  cryo.Citlali,
  pyro.Mavuika,
  electro.Olorun,
  anemo.Chasca,
  geo.Xilonen,
  dendro.Kinich,
  hydro.Mualani,
  dendro.Emilie,
  hydro.Sigewinne,
  electro.Clorinde,
  pyro.Arlecchino,
  geo.Chiori,
  anemo.Liuyun,
  geo.Navia,
  hydro.Furina,
  cryo.Wriothesley,
  hydro.Neuvillette,
  pyro.Liney,
  dendro.Baizhuer,
  pyro.Dehya,
  dendro.Alhatham,
  anemo.Wanderer,
  dendro.Nahida,
  hydro.Nilou,
  electro.Cyno,
  dendro.Tighnari,
  hydro.Yelan,
  hydro.Ayato,
  electro.Yae,
  cryo.Shenhe,
  geo.Itto,
  hydro.Kokomi,
  cryo.Aloy,
  electro.Shougun,
  pyro.Yoimiya,
  cryo.Ayaka,
  anemo.Kazuha,
  cryo.Eula,
  pyro.Hutao,
  anemo.Xiao,
  cryo.Ganyu,
  geo.Albedo,
  geo.Zhongli,
  hydro.Tartaglia,
  pyro.Klee,
  anemo.Venti,
  anemo.Qin,
  electro.Keqing,
  pyro.Diluc,
  hydro.Mona,
  cryo.Qiqi,
  geo.Kachina,
  electro.Sethos,
  pyro.Gaming,
  pyro.Chevreuse,
  cryo.Charlotte,
  cryo.Freminet,
  anemo.Linette,
  dendro.Momoka,
  dendro.Kaveh,
  cryo.Mika,
  dendro.Yaoyao,
  anemo.Faruzan,
  cryo.Layla,
  hydro.Candace,
  electro.Dori,
  dendro.Collei,
  anemo.Heizo,
  electro.Shinobu,
  geo.Yunjin,
  geo.Gorou,
  pyro.Tohma,
  electro.Sara,
  pyro.Yanfei,
  anemo.Sayu,
  cryo.Rosaria,
  pyro.Xinyan,
  cryo.Diona,
  anemo.Sucrose,
  electro.Fischl,
  electro.Lisa,
  electro.Razor,
  electro.Beidou,
  pyro.Xiangling,
  pyro.Ambor,
  pyro.Bennett,
  hydro.Xingqiu,
  hydro.Barbara,
  geo.Ningguang,
  geo.Noel,
  cryo.Kaeya,
  cryo.Chongyun,
  anemo.PlayerBoy,
  anemo.PlayerGirl,
  geo.PlayerBoy,
  geo.PlayerGirl,
  electro.PlayerBoy,
  electro.PlayerGirl,
  dendro.PlayerBoy,
  dendro.PlayerGirl,
  hydro.PlayerBoy,
  hydro.PlayerGirl,
  pyro.PlayerBoy,
  pyro.PlayerGirl,
];